spring.application.name=lms
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=postgres
spring.datasource.password=1270
jwt.secret=your_super_secret_key_which_is_long_and_secure_123456
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true